sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: wB8hTLXuzc6aat8Kl2T/CaB9X6LO8z7Ji1AyUK62t+CbZrWK2l3dWok7KFGpuRkwSLnyNP17za6m30o/aRftYzhipBtZvJ9J66ozqZuXnpsSvt0jG7WLdPjjpng2VwfTTPRgzIePfzk1hsG998qSFdTfCmr0RMiX4hrThrkGYWIJgqWmIQAhKHHGL2adQPa9qUrnJKuyIMbsQ+JnwjZA4WQ9UuaOg3jBHu70181a4Kbcw6h2RrqugH5PynaafAzP2+ju0Ei2T/cVpr1fsoWJLVCTikwSHZimtNr1uWIhrjg5TVNFcAjvUeLn2pcZOK0uyIqwCCuNJmkIKpfzlkTFz65IqMGevCab9wGzksuemi5axGHxf55+0K0i3Z2TRX22DKpYGn1YjkXEqyaWa88ZM/taZWeFCE3xJO+JFXmMY0IIjAWX8FnCeTdVdjV8AEKbk7x7/RRdJycx/VkHnmGGh1fLszPH1QTR5aXQktwA3t3fzOVlUjc7Bu1W0JhXheabjVNcEaUFPxEhPAuKbkl5ukjTE+S6v47Rnk8pXk+Cl5KwbjyLO/iNA1DfxKT0p7oRH1uqO5FUBYUKNBryo37szqjcNJYIYcIobwj50JQk16xHTY8vmn48MSWBTwv/z9kgePkx1Dtcq2poN5P8SYPA6oCq+5wZD0/RjIXMjLu9yvg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/History-of-Friedrich-II-of-Prussia---Volume-06_2106
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy